### ISSUE TITLE
Using "+" sign for string concatenation

### ISSUE THREAD

**Issue by AlbertoBN** [TzurielSelaSoftware/WindowsOptimizationToolWpfMvvmThreading#1]
Provided your framework version is 4.7.* you can use string interpolation ($) such as:

> $"Total bytes {DI.TotalBytes}, and so on"

If lower than 4.7 you should use 

> string.Format("Total Bytes {0}, and so on", DI.TotalSize)

You did a god job all and all.

**Comment by TzurielSelaSoftware** [comment]
Hi,
Thank you very much for the guidance.
Indeed, in my new projects I do use the above format to achieve performance improvement (you can see in the links below).
Anyways thank you very much and hope to learn more from you :-)

https://github.com/TzurielSelaSoftware/DatabaseTool/blob/master/DatabaseInterface/DatabaseInterface/DatabaseInterface/ViewModels/MainViewModel.cs

https://github.com/TzurielSelaSoftware/DatabaseTool/blob/master/DatabaseInterface/DatabaseInterface/DatabaseInterface/Database/MSSQL.cs

**Comment by TzurielSelaSoftware** [comment]
Done
